version: 2
updates:
  # ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/approve-authorization/server/ruby/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/create-cardholders-and-cards/server/ruby/"
    schedule:
      interval: "weekly"

  # python dependencies
  - package-ecosystem: "pip"
    directory: "/create-cardholders-and-cards/server/python/"
    schedule:
      interval: "weekly"

  # php dependencies
  - package-ecosystem: "composer"
    directory: "/create-cardholders-and-cards/server/php/"
    schedule:
      interval: "weekly"

  # node dependencies
  - package-ecosystm: "npm"
    directory: "/create-cardholders-and-cards/server/node/"
    schedule:
      interval: "weekly"

  # go dependencies
  - package-ecosystem: "gomod"
    directory: "/create-cardholders-and-cards/server/go/"
    schedule:
      interval: "weekly"

  # java dependencies
  - package-ecosystem: "maven"
    directory: "/create-cardholders-and-cards/server/java/"
    schedule:
      interval: "weekly"

  # dotnet dependencies
  - package-ecosystem: "nuget"
    directory: "/approve-authorization/server/dotnet/"
    schedule:
      interval: "weekly"
  # dotnet dependencies
  - package-ecosystem: "nuget"
    directory: "/create-cardholders-and-cards/server/dotnet/"
    schedule:
      interval: "weekly"
